### ISSUE TITLE
Cannot run "select" queries on aux_transfer.db

### ISSUE THREAD

**Issue by adamanderson** [SouthPoleTelescope/spt_dq_system#2]
None of the SQLite queries used by db_server.js should be capable of writing to the SQLite .db files. For some reason, simple "select" queries, such as:

"SELECT * FROM aux_transfer WHERE (date(aux_transfer.date) BETWEEN date('2018-02-06') AND date('2018-02-13'))"

fail when run on aux_transfer.db with the error:

Error: SQLITE_READONLY: attempt to write a readonly database errno: 8, code: 'SQLITE_READONLY'

Analogous queries run on scanify.db succeed without any problems. It is not at all clear why these select queries are trying to write the database, and why they only fail on aux_transfer.db. This issue is reproducible in an interactive node session. The error is not triggered when I make a copy of aux_transfer.db on which I have write access.

**Comment by arahlin** [comment]
Weird.  Is there an extended error code for this error too? The sqlite documentation claims there is a set of extended codes for the READONLY error... For example,  [SQLITE_READONLY_DIRECTORY](https://sqlite.org/rescode.html#readonly_directory)

**Comment by adamanderson** [comment]
The cause of this problem was that the directory containing scanify.db and aux_transfer.db also contained temporary files called scanify.db-journal and aux_transfer.db-journal. As described at https://sqlite.org/tempfiles.html the "journal" files are temporary files that are created when a modification is requested to the database. Once the modification has been made, the journal file is destroyed. If there is a crash in the middle of making the modification, the journal file will be left over, and sqlite will attempt to revert the database to the original state before the modification the next time it is opened. Apparently this includes instances when the database is read in read-only mode, hence the counterintuitive behavior in which opening a database in read-only mode fails because it can't write to the database. Deleting the journal files fixed the problem. Thanks to Sasha for the idea to try deleting the journal files.
